/**
 * Merger.
 *
 * Groups TestArtifacts by target filename and stitches each group into a
 * single Playwright .spec.ts file:
 *   - Collects unique imports from each artifact's code, emits them once.
 *   - Concatenates the remaining bodies, separated by blank lines.
 *   - Adds a top header comment with traceability info.
 *
 * Artifacts marked generated_ok=false are skipped (their stub code is kept
 * separately in failures[] for the report).
 */

import type { TestArtifact } from '../types.js';

export interface MergedSpec {
  filename: string;
  page_ids: string[];
  test_case_ids: string[];
  code: string;
}

export interface MergeResult {
  specs: MergedSpec[];
  failures: TestArtifact[];
}

export function mergeArtifacts(artifacts: TestArtifact[]): MergeResult {
  const successes = artifacts.filter((a) => a.generated_ok);
  const failures = artifacts.filter((a) => !a.generated_ok);

  // Group by filename
  const groups = new Map<string, TestArtifact[]>();
  for (const a of successes) {
    const list = groups.get(a.filename) ?? [];
    list.push(a);
    groups.set(a.filename, list);
  }

  const specs: MergedSpec[] = [];
  for (const [filename, group] of groups) {
    specs.push(buildSpec(filename, group));
  }

  // Stable order for deterministic output
  specs.sort((a, b) => a.filename.localeCompare(b.filename));

  return { specs, failures };
}

function buildSpec(filename: string, artifacts: TestArtifact[]): MergedSpec {
  const importSet = new Set<string>();
  const bodies: string[] = [];

  for (const artifact of artifacts) {
    const { imports, body } = splitImportsAndBody(artifact.code);
    for (const imp of imports) importSet.add(imp);
    bodies.push(annotate(artifact, body));
  }

  // Always include the standard Playwright test import
  importSet.add(`import { test, expect } from '@playwright/test';`);

  const header = buildHeader(filename, artifacts);
  const importBlock = Array.from(importSet).sort().join('\n');
  const body = bodies.join('\n\n');

  return {
    filename,
    page_ids: dedupe(artifacts.map((a) => a.page_id)),
    test_case_ids: artifacts.map((a) => a.test_case_id),
    code: `${header}\n\n${importBlock}\n\n${body}\n`,
  };
}

function buildHeader(filename: string, artifacts: TestArtifact[]): string {
  const pageUrl = artifacts[0]?.page_url ?? '';
  const tcList = artifacts.map((a) => `// - ${a.test_case_id} (${a.attack_id})`).join('\n');
  return `/**
 * Auto-generated by test-generator.
 * File: ${filename}
 * Page: ${pageUrl}
 * Test cases:
${tcList}
 *
 * Do not edit by hand. Re-run the generator to refresh.
 */`;
}

/**
 * Add a short prefix comment to each test block for traceability.
 * Does not touch the code itself — the LLM is responsible for using the
 * TestCase id in the test name.
 */
function annotate(artifact: TestArtifact, body: string): string {
  return `// ----- ${artifact.test_case_id}: ${artifact.attack_id} -----\n${body.trim()}`;
}

/**
 * Split a code string into top-level import statements and the rest.
 * Only matches `import ... from '...';` lines. Anything else is body.
 */
function splitImportsAndBody(code: string): { imports: string[]; body: string } {
  const imports: string[] = [];
  const bodyLines: string[] = [];
  for (const line of code.split('\n')) {
    if (/^\s*import\s.+from\s+['"][^'"]+['"]\s*;?\s*$/.test(line)) {
      imports.push(line.trim());
    } else {
      bodyLines.push(line);
    }
  }
  return { imports, body: bodyLines.join('\n').trim() };
}

function dedupe<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}
