/**
 * Stable selector generator (Node-side).
 *
 * Takes an ElementInfo snapshot collected from the browser, and produces:
 *   - selector: a CSS-like string Playwright understands (page.locator(selector))
 *   - playwrightLocator: the recommended Playwright locator expression
 *   - alternates: other valid selectors in priority order
 *
 * Priority (Playwright's recommended order):
 *   1. test-id (data-testid)
 *   2. role + name      (page.getByRole)
 *   3. label            (page.getByLabel)
 *   4. placeholder      (page.getByPlaceholder)
 *   5. text             (page.getByText)
 *   6. id               (page.locator('#id'))
 *   7. name             (page.locator('[name="..."]'))
 *   8. CSS path         (last resort)
 */

import type { ElementInfo, SelectorResult } from './types.js';

const MAX_TEXT_LEN = 80;

export function generateSelector(info: ElementInfo): SelectorResult {
  const alternates: string[] = [];
  let chosen:
    | {
        selector: string;
        playwrightLocator: string;
        strategy: SelectorResult['strategy'];
      }
    | null = null;

  // 1. test-id
  if (info.testId && info.testIdAttribute) {
    const selector = `[${info.testIdAttribute}="${escapeAttr(info.testId)}"]`;
    const locator =
      info.testIdAttribute === 'data-testid'
        ? `page.getByTestId('${escapeJs(info.testId)}')`
        : `page.locator('${escapeJs(selector)}')`;
    chosen = { selector, playwrightLocator: locator, strategy: 'test-id' };
  }

  // 2. role + name (only if there's an accessible name)
  const accessibleName = info.ariaLabel || info.label || info.text;
  if (info.role && accessibleName) {
    const nameText = truncate(accessibleName, MAX_TEXT_LEN);
    const roleLocator = `page.getByRole('${escapeJs(info.role)}', { name: '${escapeJs(nameText)}' })`;
    const selectorStr = `role=${info.role}[name="${escapeAttr(nameText)}"]`;
    if (!chosen) {
      chosen = { selector: selectorStr, playwrightLocator: roleLocator, strategy: 'role-name' };
    } else {
      alternates.push(roleLocator);
    }
  }

  // 3. label (for inputs / form fields)
  if (info.label) {
    const labelText = truncate(info.label, MAX_TEXT_LEN);
    const locator = `page.getByLabel('${escapeJs(labelText)}')`;
    const selectorStr = `label=${labelText}`;
    if (!chosen) {
      chosen = { selector: selectorStr, playwrightLocator: locator, strategy: 'label' };
    } else {
      alternates.push(locator);
    }
  }

  // 4. placeholder
  if (info.placeholder) {
    const ph = truncate(info.placeholder, MAX_TEXT_LEN);
    const locator = `page.getByPlaceholder('${escapeJs(ph)}')`;
    const selectorStr = `[placeholder="${escapeAttr(ph)}"]`;
    if (!chosen) {
      chosen = { selector: selectorStr, playwrightLocator: locator, strategy: 'placeholder' };
    } else {
      alternates.push(locator);
    }
  }

  // 5. text (for buttons / links primarily)
  if (info.text && (info.tag === 'button' || info.tag === 'a') && !chosen) {
    const txt = truncate(info.text, MAX_TEXT_LEN);
    const locator = `page.getByText('${escapeJs(txt)}', { exact: true })`;
    const selectorStr = `text="${escapeAttr(txt)}"`;
    chosen = { selector: selectorStr, playwrightLocator: locator, strategy: 'text' };
  } else if (info.text && (info.tag === 'button' || info.tag === 'a')) {
    const txt = truncate(info.text, MAX_TEXT_LEN);
    alternates.push(`page.getByText('${escapeJs(txt)}', { exact: true })`);
  }

  // 6. id (only if it doesn't look auto-generated)
  if (info.id && looksStableId(info.id)) {
    const selectorStr = `#${cssEscape(info.id)}`;
    const locator = `page.locator('${escapeJs(selectorStr)}')`;
    if (!chosen) {
      chosen = { selector: selectorStr, playwrightLocator: locator, strategy: 'id' };
    } else {
      alternates.push(locator);
    }
  }

  // 7. name attribute (very useful for form inputs)
  if (info.name) {
    const selectorStr = `${info.tag}[name="${escapeAttr(info.name)}"]`;
    const locator = `page.locator('${escapeJs(selectorStr)}')`;
    if (!chosen) {
      chosen = { selector: selectorStr, playwrightLocator: locator, strategy: 'name' };
    } else {
      alternates.push(locator);
    }
  }

  // 8. fallback: CSS path
  if (!chosen) {
    const locator = `page.locator('${escapeJs(info.cssPath)}')`;
    chosen = { selector: info.cssPath, playwrightLocator: locator, strategy: 'css-path' };
  } else {
    alternates.push(`page.locator('${escapeJs(info.cssPath)}')`);
  }

  return {
    selector: chosen.selector,
    playwrightLocator: chosen.playwrightLocator,
    alternates: dedupe(alternates),
    strategy: chosen.strategy,
  };
}

/**
 * Heuristic: skip IDs that look auto-generated by frameworks (React, Vue, Angular).
 */
function looksStableId(id: string): boolean {
  if (id.length === 0) return false;
  // CSS-uuid-ish: more than one dash + alphanumeric mix
  if (/^[a-f0-9-]{20,}$/i.test(id)) return false;
  // emotion/styled-components or generated: contains `:` or starts with digit
  if (id.includes(':')) return false;
  if (/^\d/.test(id)) return false;
  if (id.length > 40) return false;
  return true;
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max).trim() : s;
}

function escapeAttr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function escapeJs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function cssEscape(s: string): string {
  return s.replace(/(["\\#.:>+~*=^$|()[\]{}/\s])/g, '\\$1');
}

function dedupe(arr: string[]): string[] {
  return Array.from(new Set(arr));
}
